[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "yaml2rpm"
authors = [{name='ppapadop', email='philip.papadopoulos@gmail.com'}, {name = "npw", email = "nadya.williams@gmail.com"}]

dynamic = ["version", "description"]
